name: egrocer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.18+68

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  http: ^0.13.6
  connectivity_plus: ^4.0.1
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  flutter_widget_from_html: ^0.15.1
  country_code_picker: ^3.0.0

  otp_text_field: ^1.1.3
  telephony: ^0.2.0
  flutter_localizations:
    sdk: flutter
  lottie: ^3.0.0
  geolocator: ^12.0.0 #for user location
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.0  #for map
  geocoding: ^3.0.0
  speech_to_text: ^6.1.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  file_picker: ^8.0.6 #for pick the files for profile picture
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  share_plus: ^10.0.0

  intl: ^0.19.0
  razorpay_flutter: any
  #flutter_paystack: ^1.0.7
#  flutter_stripe: ^11.0.0
  external_path: ^1.0.3
  open_filex: ^4.4.0
#  paytm: ^3.0.1
  version: ^3.0.2
  package_info_plus: ^4.0.2
  awesome_notifications: ^0.9.3+1
  permission_handler: ^11.3.1
  flutter_swipe_button: ^2.1.3
  webview_flutter: ^4.8.0
  vibration: ^1.9.0
  google_fonts: ^4.0.4
  image_cropper: ^4.0.1

  video_thumbnail: ^0.5.3
  youtube_player_flutter: ^9.0.1
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.3.1
  blinking_text: ^1.0.4
  facebook_app_events: ^0.19.2
  google_api_headers: ^1.6.0 # or the latest version

  # Firebase auths
  firebase_messaging: ^15.0.4
  firebase_app_check: any
  firebase_dynamic_links: ^6.0.4  #for share product
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  #get: ^4.6.6
  wakelock_plus: ^1.2.1
  phonepe_payment_sdk: ^2.0.3
  crypto: ^3.0.3
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  sizer: ^3.0.3

dependency_overrides:
  country_code_picker: ^3.0.0

  intl: ^0.19.0
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/animation/
    - assets/mapTheme/
    - assets/fonts/
    - assets/language/
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/light.ttf
          weight: 300
        - asset: assets/fonts/regular.ttf
          weight: 400
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/bold.ttf
          weight: 700